default:
  tags:
    - test

stages:
  - test
  - sonar
  - build

before_script:
  - if [ -f Dockerfile.test ]; then docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD gitint.elewise.com:5050; fi

sonarqube-check:
  stage: sonar
  script:
    - if [ ! -f tsconfig.json ]; then tsc --init; fi
    - bash ./sonarqube.sh
  allow_failure: true

test:
  stage: test
  script:
    - if [ ! -f Dockerfile.test ]; then exit 0; fi
    - docker build -t test -f Dockerfile.test .
    - CONTAINER_ID=$(docker create test) # создает контейнер, но не запускает его
    - docker cp $CONTAINER_ID:/app/coverage.out .
    - docker rm $CONTAINER_ID
  artifacts:
    paths:
      - coverage.out

build:
  stage: build
  script:
    - if [ ! -f Dockerfile ]; then exit 0; fi
    - TAG_NAME="latest"
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then TAG_NAME="master"; fi
    - docker build -t $IMAGE_NAME:$TAG_NAME .
    - docker push $IMAGE_NAME:$TAG_NAME
